cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: eck-operator
  labels:
    name: eck-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
  labels:
    name: logging
EOF
